name: deploy
on: 
    push: 
        branches: [main]
jobs: 
    build:
        runs-on: ubuntu

        steps:

        - uses: actions/checkou@v2

        - name: QEMU
          uses: docker/setup-qemu-action@v1

        - name: Docker Buildx
          uses: docker/setup-buildx-action@v1

        - name: login to docker hub.
          uses: docker/login-action@v1
          with: 
            username: $ {{ secrets.DOCKERHUB_USERNAME }}
            password: $ {{ secrets.DOCKERHUB_TOKEN }}
        - name: bump version 
          id: tagging
          uses: mathieudutour/github-tag-action@v4.5
          with: 
            github_token: $ {{ secrets.GITHUB_TOKEN }}
        
        - name: buld and push 
          id: docker_build
          uses: docker/build-push-action@v2
          with: 
            push: true
            context: .
            file: ./Dockerfile
            tags: ademirpereira/teste-cd-b:$ {{ steps.tagging.outputs.new_version }}

        